name: Test
on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  test:
    name: Code & process tests
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [linux-latest]
        goarch: [amd64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: n8maninger/action-golang-test@v1
        name: Run tests
        with:
          package: github.com/axllent/golp/app
          show-passed-tests: true
